# Dependabot configuration:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly" # avoid updating daily, it is spammy
      day: "sunday"
    open-pull-requests-limit: 3
#    target-branch: "develop"
#    ignore:
#      - versions: ["x.x.*"] # temporary, ignore patch updates
